# configure.py
######################

import os
import sipconfig

# The name of the SIP build file generated by SIP and used by the build system.
build_file = "psapp.sbf"

sipIncludePath ='C:\Python27\sip\PyQt5'

# Get the SIP configuration information.
config = sipconfig.Configuration()

#sipExe = config.sip_bin
sipExe = "C:\Python27\sip.exe"

command = " ".join([sipExe, "-w", "-e", "-t WS_WIN -x PyQt_NoPrintRangeBug -t Qt_5_7_0 -x Py_v2 -g -o -a .\psapp.api -j 1", "-c", ".", "-b", build_file, "-I", sipIncludePath, "psapp.sip"])

# Run SIP to generate the code.
os.system(command)

# Create the Makefile.
makefile = sipconfig.SIPModuleMakefile(config, build_file)

# Add include path
makefile.INCDIR._macro.append("C:\Qt\Qt5.7.0\\5.7\msvc2013\include")
makefile.INCDIR._macro.append("C:\Qt\Qt5.7.0\\5.7\msvc2013\include\QtCore")

makefile.INCDIR._macro.append(".\..\PythonBinding")

# Add library path

makefile.LIBDIR._macro.append("C:\Qt\Qt5.7.0\\5.7\msvc2013\lib")
makefile.LIBDIR._macro.append(".\..\Win32\Release")

# Add the library we are wrapping.  The name doesn't include any platform
# specific prefixes or extensions (e.g. the "lib" prefix on UNIX, or the
# ".dll" extension on Windows).
makefile.extra_libs = ["PythonBinding", "Qt5Core"]

makefile._install_dir = ".\..\Win32\Release\python"

# Generate the Makefile itself.
makefile.generate()
#####################